# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x'

- script: dotnet restore $(solution)   
  displayName: 'Restore solution'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --collect:"XPlant Code Coverage"
  displayName: 'Run test'

- task: Docker@2
  inputs:
    containerRegistry: 'acrapidemogrsantana'
    repository: 'api-dio-tempo'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'